apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "backend-k8s-test-hpa"
  labels:
    app: "backend-k8s-test"
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: backend-k8s-test
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80